In [2]:
import pandas as pd

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("C:\\Users\\lokesh.s\\ecommerce sales data.csv")
print(df)

                          Product Quantity Ordered Price Each  \
0            USB-C Charging Cable                2      11.95
1                             NaN              NaN        NaN
2      Bose SoundSport Headphones                1      99.99
3                    Google Phone                1        600
4                Wired Headphones                1      11.99
...                           ...              ...        ...
30389  Bose SoundSport Headphones                1      99.99
30390      AAA Batteries (4-pack)                3       2.99
30391       AA Batteries (4-pack)                1       3.84
30392        USB-C Charging Cable                1      11.95
30393       AA Batteries (4-pack)                1       3.84

            Order Date Purchase Address
0       4/19/2019 8:46           Dallas
1                  NaN              NaN
2       4/7/2019 22:30           Boston
3      4/12/2019 14:38      Los Angeles
4      4/12/2019 14:38      Los Angeles
...                ...              ...
30389  8/29/2019 22:19    San Francisco
30390  8/31/2019 16:26           Boston
30391    8/2/2019 7:25          Seattle
30392   8/8/2019 12:10    San Francisco
30393   8/16/2019 8:13      Los Angeles

[30394 rows x 5 columns]

In [5]:
df

,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,USB-C Charging Cable,2,11.95,4/19/2019 8:46,Dallas
1,NaN,NaN,NaN,NaN,NaN
2,Bose SoundSport Headphones,1,99.99,4/7/2019 22:30,Boston
3,Google Phone,1,600,4/12/2019 14:38,Los Angeles
4,Wired Headphones,1,11.99,4/12/2019 14:38,Los Angeles
...,...,...,...,...,...
30389,Bose SoundSport Headphones,1,99.99,8/29/2019 22:19,San Francisco
30390,AAA Batteries (4-pack),3,2.99,8/31/2019 16:26,Boston
30391,AA Batteries (4-pack),1,3.84,8/2/2019 7:25,Seattle
30392,USB-C Charging Cable,1,11.95,8/8/2019 12:10,San Francisco
30393,AA Batteries (4-pack),1,3.84,8/16/2019 8:13,Los Angeles

In [6]:
df = df.dropna(how='all')
df

,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,USB-C Charging Cable,2,11.95,4/19/2019 8:46,Dallas
2,Bose SoundSport Headphones,1,99.99,4/7/2019 22:30,Boston
3,Google Phone,1,600,4/12/2019 14:38,Los Angeles
4,Wired Headphones,1,11.99,4/12/2019 14:38,Los Angeles
5,Wired Headphones,1,11.99,4/30/2019 9:27,Los Angeles
...,...,...,...,...,...
30389,Bose SoundSport Headphones,1,99.99,8/29/2019 22:19,San Francisco
30390,AAA Batteries (4-pack),3,2.99,8/31/2019 16:26,Boston
30391,AA Batteries (4-pack),1,3.84,8/2/2019 7:25,Seattle
30392,USB-C Charging Cable,1,11.95,8/8/2019 12:10,San Francisco
30393,AA Batteries (4-pack),1,3.84,8/16/2019 8:13,Los Angeles

In [7]:
df['Product'].value_counts()

Product
Lightning Charging Cable      3556
USB-C Charging Cable          3423
AA Batteries (4-pack)         3419
AAA Batteries (4-pack)        3329
Wired Headphones              3082
Apple Airpods Headphones      2515
Bose SoundSport Headphones    2151
27in FHD Monitor              1220
iPhone                        1131
34in Ultrawide Monitor        1031
27in 4K Gaming Monitor        1000
Google Phone                   939
Flatscreen TV                  789
Macbook Pro Laptop             752
ThinkPad Laptop                667
20in Monitor                   649
Vareebadd Phone                361
LG Dryer                       123
LG Washing Machine             109
Product                         61
Name: count, dtype: int64

In [8]:
df['Price Each'].value_counts()

Price Each
14.95         3556
11.95         3423
3.84          3419
2.99          3329
11.99         3082
150           2515
99.99         2151
149.99        1220
600           1171
700           1131
379.99        1031
389.99        1000
300            789
1700           752
999.99         667
109.99         649
400            361
Price Each      61
Name: count, dtype: int64

In [9]:
df = df.drop_duplicates()

In [10]:
print(df)

                          Product Quantity Ordered Price Each  \
0            USB-C Charging Cable                2      11.95
2      Bose SoundSport Headphones                1      99.99
3                    Google Phone                1        600
4                Wired Headphones                1      11.99
5                Wired Headphones                1      11.99
...                           ...              ...        ...
30389  Bose SoundSport Headphones                1      99.99
30390      AAA Batteries (4-pack)                3       2.99
30391       AA Batteries (4-pack)                1       3.84
30392        USB-C Charging Cable                1      11.95
30393       AA Batteries (4-pack)                1       3.84

            Order Date Purchase Address
0       4/19/2019 8:46           Dallas
2       4/7/2019 22:30           Boston
3      4/12/2019 14:38      Los Angeles
4      4/12/2019 14:38      Los Angeles
5       4/30/2019 9:27      Los Angeles
...                ...              ...
30389  8/29/2019 22:19    San Francisco
30390  8/31/2019 16:26           Boston
30391    8/2/2019 7:25          Seattle
30392   8/8/2019 12:10    San Francisco
30393   8/16/2019 8:13      Los Angeles

[30137 rows x 5 columns]

In [11]:
df

,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,USB-C Charging Cable,2,11.95,4/19/2019 8:46,Dallas
2,Bose SoundSport Headphones,1,99.99,4/7/2019 22:30,Boston
3,Google Phone,1,600,4/12/2019 14:38,Los Angeles
4,Wired Headphones,1,11.99,4/12/2019 14:38,Los Angeles
5,Wired Headphones,1,11.99,4/30/2019 9:27,Los Angeles
...,...,...,...,...,...
30389,Bose SoundSport Headphones,1,99.99,8/29/2019 22:19,San Francisco
30390,AAA Batteries (4-pack),3,2.99,8/31/2019 16:26,Boston
30391,AA Batteries (4-pack),1,3.84,8/2/2019 7:25,Seattle
30392,USB-C Charging Cable,1,11.95,8/8/2019 12:10,San Francisco
30393,AA Batteries (4-pack),1,3.84,8/16/2019 8:13,Los Angeles

In [12]:
df['Price Each'].value_counts()

Price Each
14.95         3529
3.84          3411
11.95         3404
2.99          3320
11.99         3069
150           2504
99.99         2145
149.99        1219
600           1170
700           1127
379.99        1026
389.99         999
300            787
1700           750
999.99         667
109.99         648
400            361
Price Each       1
Name: count, dtype: int64

In [13]:
index = df[df['Price Each'] == 'Price Each'].index[0]
print(index)

519

In [14]:
df = df.drop(519)

In [15]:
df

,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,USB-C Charging Cable,2,11.95,4/19/2019 8:46,Dallas
2,Bose SoundSport Headphones,1,99.99,4/7/2019 22:30,Boston
3,Google Phone,1,600,4/12/2019 14:38,Los Angeles
4,Wired Headphones,1,11.99,4/12/2019 14:38,Los Angeles
5,Wired Headphones,1,11.99,4/30/2019 9:27,Los Angeles
...,...,...,...,...,...
30389,Bose SoundSport Headphones,1,99.99,8/29/2019 22:19,San Francisco
30390,AAA Batteries (4-pack),3,2.99,8/31/2019 16:26,Boston
30391,AA Batteries (4-pack),1,3.84,8/2/2019 7:25,Seattle
30392,USB-C Charging Cable,1,11.95,8/8/2019 12:10,San Francisco
30393,AA Batteries (4-pack),1,3.84,8/16/2019 8:13,Los Angeles

In [16]:
df['Price Each'].value_counts()

Price Each
14.95     3529
3.84      3411
11.95     3404
2.99      3320
11.99     3069
150       2504
99.99     2145
149.99    1219
600       1170
700       1127
379.99    1026
389.99     999
300        787
1700       750
999.99     667
109.99     648
400        361
Name: count, dtype: int64

In [17]:
df['date'] = df['Order Date'].dt.date
df['time'] = df['Order Date'].dt.time

AttributeError: Can only use .dt accessor with datetimelike values

In [18]:
df['datetime'] = pd.to_datetime(df['Order Date'])

In [19]:
df['date'] = df['Order Date'].dt.date
df['time'] = df['Order Date'].dt.time

AttributeError: Can only use .dt accessor with datetimelike values

object

In [42]:
df['datetime'] = pd.to_datetime(df['Order Date'])

In [43]:
print(df['datetime'].dtype)

datetime64[ns]

In [45]:
df['date'] = df['datetime'].dt.date
df['time'] = df['datetime'].dt.time

In [46]:
df

,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,datetime,date,time
0,USB-C Charging Cable,2,11.95,4/19/2019 8:46,Dallas,2019-04-19 08:46:00,2019-04-19,08:46:00
2,Bose SoundSport Headphones,1,99.99,4/7/2019 22:30,Boston,2019-04-07 22:30:00,2019-04-07,22:30:00
3,Google Phone,1,600,4/12/2019 14:38,Los Angeles,2019-04-12 14:38:00,2019-04-12,14:38:00
4,Wired Headphones,1,11.99,4/12/2019 14:38,Los Angeles,2019-04-12 14:38:00,2019-04-12,14:38:00
5,Wired Headphones,1,11.99,4/30/2019 9:27,Los Angeles,2019-04-30 09:27:00,2019-04-30,09:27:00
...,...,...,...,...,...,...,...,...
30389,Bose SoundSport Headphones,1,99.99,8/29/2019 22:19,San Francisco,2019-08-29 22:19:00,2019-08-29,22:19:00
30390,AAA Batteries (4-pack),3,2.99,8/31/2019 16:26,Boston,2019-08-31 16:26:00,2019-08-31,16:26:00
30391,AA Batteries (4-pack),1,3.84,8/2/2019 7:25,Seattle,2019-08-02 07:25:00,2019-08-02,07:25:00
30392,USB-C Charging Cable,1,11.95,8/8/2019 12:10,San Francisco,2019-08-08 12:10:00,2019-08-08,12:10:00
30393,AA Batteries (4-pack),1,3.84,8/16/2019 8:13,Los Angeles,2019-08-16 08:13:00,2019-08-16,08:13:00

In [47]:
df = df.drop(columns=['datetime'])

In [48]:
df = df.drop(columns=['Order Date'])

In [49]:
df

,Product,Quantity Ordered,Price Each,Purchase Address,date,time
0,USB-C Charging Cable,2,11.95,Dallas,2019-04-19,08:46:00
2,Bose SoundSport Headphones,1,99.99,Boston,2019-04-07,22:30:00
3,Google Phone,1,600,Los Angeles,2019-04-12,14:38:00
4,Wired Headphones,1,11.99,Los Angeles,2019-04-12,14:38:00
5,Wired Headphones,1,11.99,Los Angeles,2019-04-30,09:27:00
...,...,...,...,...,...,...
30389,Bose SoundSport Headphones,1,99.99,San Francisco,2019-08-29,22:19:00
30390,AAA Batteries (4-pack),3,2.99,Boston,2019-08-31,16:26:00
30391,AA Batteries (4-pack),1,3.84,Seattle,2019-08-02,07:25:00
30392,USB-C Charging Cable,1,11.95,San Francisco,2019-08-08,12:10:00
30393,AA Batteries (4-pack),1,3.84,Los Angeles,2019-08-16,08:13:00

In [50]:
df['Product'].value_counts()

Product
Lightning Charging Cable      3529
AA Batteries (4-pack)         3411
USB-C Charging Cable          3404
AAA Batteries (4-pack)        3320
Wired Headphones              3069
Apple Airpods Headphones      2504
Bose SoundSport Headphones    2145
27in FHD Monitor              1219
iPhone                        1127
34in Ultrawide Monitor        1026
27in 4K Gaming Monitor         999
Google Phone                   938
Flatscreen TV                  787
Macbook Pro Laptop             750
ThinkPad Laptop                667
20in Monitor                   648
Vareebadd Phone                361
LG Dryer                       123
LG Washing Machine             109
Name: count, dtype: int64

In [22]:
df.to_excel('lokesh5.xlsx', index=False)